# Generated by Django 4.2.17 on 2025-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='street',
            field=models.CharField(default='Galal street', max_length=50),
            preserve_default=False,
        ),
    ]
