# Generated by Django 5.1.4 on 2024-12-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to='image/upload'),
            preserve_default=False,
        ),
    ]
